version: "3"
services:
  web:
    image: nginx
    links:
      - kbase
    volumes:
      - ./nginx/kbase.conf:/etc/nginx/conf.d/kbase.conf:ro
      - ./nginx:/etc/nginx/ssl/
      - ./log/nginx:/var/log/nginx/
    ports:
      - 80:80
      - 443:443

  kbase:
    image: denley/kbase
    expose:
      - 4000